### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ss0912** [fuxihao66/ODI-TestProject#1]
![Snipaste_2024-07-03_15-52-44](https://github.com/fuxihao66/ODI-TestProject/assets/173356514/96cf4a12-84e0-4d70-9631-d82fb906140b)

![Snipaste_2024-07-03_15-50-02](https://github.com/fuxihao66/ODI-TestProject/assets/173356514/3945f608-d2e4-4971-89eb-c0b3fdf2ff6d)
I'm using Unreal Engine version 5.2.1 and VS version 2019. The project fails to be compiled, as shown in the following figure.

**Comment by fuxihao66** [comment]
Before opening this project, you should right click on the .uproject file to "switch Unreal Engine Version" and then "Generate Visual Studio project files". Then you can open the .sln file and build the project.

**Comment by ss0912** [comment]
Thank you very much for your answer. I tried to use VS2019 to generate the project, but the error as shown in the picture occurred. Do you know how to solve it?
![Snipaste_2024-07-04_14-27-02](https://github.com/fuxihao66/ODI-TestProject/assets/173356514/75b9a9ac-6f55-4867-a751-a5366f05bb2f)

**Comment by fuxihao66** [comment]
If official Unreal Engine is used (downloaded from epic games launcher), please download protobuf from [here](https://github.com/protocolbuffers/protobuf/releases/download/v3.18.0/protobuf-cpp-3.18.0.zip), then copy BASE_DIR/protobuf-3.18.0/src/google/protobuf to UE_BASE_DIR/Engine/Source/ThirdParty/Protobuf/3.18.0/include/google.

**Comment by ss0912** [comment]
Thank you very much for your answer! I am now able to run the project in Unreal Engine, but when I execute the  **r.RealtimeStyleTransfer.Enable 1** command, the stylized inference result is called. I would like to ask, how to use your extrapolation frame inference model?

**Comment by fuxihao66** [comment]
The "ExtraNet" branch is used for extrapolation frame inference. But currently it can only be used for gpu time testing, as I don't have time to implement the prerequisite passes (buffer preparation, image warping, etc). If you want to use it for extrapolation, you need to implement these parts yourselves.

**Comment by ss0912** [comment]
Are you saying that "ExtraNet" is not currently being used in the Unreal Engine rendering pipeline?

**Comment by ss0912** [comment]
Are you saying that ExtraNet is not currently being used in the Unreal Engine rendering pipeline? So the "ODI" plugin you provided doesn't implement the "ExtraNet" functionality in Unreal Engine? Thanks again for your patience in answering.

**Comment by fuxihao66** [comment]
Yes, it only has the "inference" step of ExtraNet Neural Network, but not the entire pipeline of frame extrapolation (including buffer preparation, image warping, etc).
