### ISSUE TITLE
About the issue of onnx optimization

### ISSUE THREAD

**Issue by Sodiride123** [fuxihao66/ODI-TestProject#2]
Hi,
I wonder if it is compulsory to do the model optimization using the ORT Graph optimization, like below
![optim](https://github.com/user-attachments/assets/41bea85e-aba8-4d3e-abab-c634feee0f1a)\

I am trying my own super-sampling model, the original candy-9 model and optimized candy-9 using above code, the project can be complied successfully, but the UE crashed for the all three models and popped the error below after Enter r.RealtimeStyleTransfer.Enable 1
![error](https://github.com/user-attachments/assets/3bc52fad-ec9b-407c-9a99-f2cf92e3740c)

But everything works well if using the model you provided. 
I do not think it is the problems of the operator types since the 3 model I used have the quite same operator types as the models you provided like ExtraNet and optimized candy-9. Have you had the same issue before?

**Comment by fuxihao66** [comment]
You can use https://netron.app/ to visualize these models to compare their differences. Maybe the opset version are incompatible with my implementation.
![Screenshot 2024-10-29 215418](https://github.com/user-attachments/assets/cace1ee1-a36f-4b42-961c-dfdcac9cb6ed)

**Comment by Sodiride123** [comment]
I see, thx.
